# Copyright (c) 2025 TNET
# SPDX-License-Identifier: BSD-2-Clause OR MIT OR Apache-2.0
services:
  nginx:
    # use GHCR image
    image: ghcr.io/tnetmoe/distroless-nginx:mainline
    # drop all capabilities
    cap_drop:
      - ALL
    cap_add:
      # Needed for ports below 1024
      - CAP_NET_BIND_SERVICE
    security_opt:
      # prevents the container from gaining any additional privileges
      - no-new-privileges:true
    restart: unless-stopped
    # make fs read-only
    read_only: true
    tmpfs:
      # mount /tmp as tmpfs
      - "/tmp:exec,uid=1002,gid=1000"
    # expose port 80
    ports:
      - "80:80"
    volumes:
      # Override default.conf with custom configuration
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
