name: Scheduled Docker Image Vulnerability Scan

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  GHCR_REPO: ghcr.io/${{ github.repository }}

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [stable, mainline]
        image: [nginx, modsecurity]
    steps:
      - name: Image Tag
        id: set_scan_tag
        run: |
          if [ "${{ matrix.version }}" == "stable" ]; then
            BASE_TAG="stable"
          else
            BASE_TAG="mainline"
          fi
          if [ "${{ matrix.image }}" == "modsecurity" ]; then
            SCAN_TAG="${BASE_TAG}-modsecurity"
          else
            SCAN_TAG="${BASE_TAG}"
          fi
          echo "SCAN_TAG=${SCAN_TAG}" >> "$GITHUB_ENV"
          echo "Base tag for scanning: ${SCAN_TAG}"

      - name: Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.GHCR_REPO }}:${{ env.SCAN_TAG }}
          format: table
          # Fail if vulnerabilities are found.
          exit-code: '1'
